### ISSUE TITLE
runkit_function_rename cant rename sleep to sleep__

### ISSUE THREAD

**Issue by wuchuguang** [runkit7/runkit7#119]
runkit_function_rename('sleep', 'sleep__');// false

function test(){}

runkit_function_rename('test', 'test__');// true

cant rename inner function ?

**Comment by TysonAndre** [comment]
http://php.net/manual/en/runkit.configuration.php#ini.runkit.internal-override - runkit7.internal_override=1 must be included in your php.ini or arguments to PHP (e.g. `php -d runkit.internal_override=1 -a`)
