### ISSUE TITLE
zend_mm_heap corrupted in php 7.2.1 with closure in runkit_function_redefine

### ISSUE THREAD

**Issue by c3037** [runkit7/runkit7#127]
Good day. Fund error in php 7.2.1

// WORKS
/*
function test($a) {
	return $a;
}
	
$newBehavior = function($a) {
	return strrev($a);
};

//replace
runkit_function_copy('test', '__old');
runkit_function_redefine('test', $newBehavior);
echo test('12'); // 21

// restore
runkit_function_remove('test');
runkit_function_copy('__old', 'test');
runkit_function_remove('__old');
echo test('21'); // 21
*/

// CORRUPTED (zend_mm_heap corrupted)
$newBehavior = function() {
	return 'new behavior';
};

//replace
runkit_function_copy('time', '__old');
runkit_function_redefine('time', $newBehavior);
echo time();

// restore
runkit_function_remove('time');
runkit_function_copy('__old', 'time');
runkit_function_remove('__old');
echo time();

**Comment by TysonAndre** [comment]
This is likely to have the same cause as 
https://github.com/runkit7/runkit7/issues/123

As the readme says, 7.2 isn't supported yet due to changes in PHP internals.
