### ISSUE TITLE
appveyor windows built is not generated in a fork with visual studio 2017 (for php 7.2)

### ISSUE THREAD

**Issue by pilathraj** [runkit7/runkit7#131]
Creating library C:\projects\runkit7\x64\Release\php_runkit.lib and object C:\projects\runkit7\x64\Release\php_runkit.exp
runkit.obj : error LNK2019: unresolved external symbol php_runkit_globals_ctor referenced in function zm_startup_runkit
C:\projects\runkit7\x64\Release\php_runkit.dll : fatal error LNK1120: 1 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\link.exe"' : return code '0x460'
Stop.
Command exited with code 2

Reference : https://github.com/pilathraj/runkit7.1/blob/master/appveyor.yml

**Comment by TysonAndre** [comment]
This issue doesn't mention the commit you're using. (e.g. I see https://github.com/pilathraj/runkit7.1/commit/23dc448089059335b89711f2e4bfe7d293d1d912). You aren't using github's forking, so it's hard compare across repos.

**Comment by pilathraj** [comment]
information updated in bug #132.

**Comment by TysonAndre** [comment]
You can retry with the latest master branch.

I encountered a similar issue with PHP_RUNKIT_ITERATE_THROUGH_OBJECTS_STORE_BEGIN when trying to use windows PECL builds (i.e. using php's builds, done outside of the php-src directory)

- HAVE_CONFIG_H was undefined. No file called config.h was being generated for some reason. A file called main/config.pickle.h existed (I'm assuming it is an intermediate file).
- I gave up and added the macros to CFLAGS_RUNKIT directly in config.w32

**Comment by pilathraj** [comment]
Thanks it's working fine now , i can create a built for php 7.2. 
Thank you very much.
