### ISSUE TITLE
Support for sandbox

### ISSUE THREAD

**Issue by Slavenin** [runkit7/runkit7#136]
Hi!
Do you plan to return sandbox support? I specially compiled the thread-safe php 7.2 from the source. And then such a epic fail ...

**Comment by TysonAndre** [comment]
There's a lot of things which are planned (bug fixes, replacement features) before reintroducing sandbox support.

I tried supporting this earlier but ran into issues getting the switching to actually work properly, and the thread API usage documentation wasn't there. See https://github.com/runkit7/runkit7/issues/114

https://github.com/runkit7/runkit7#features

> Runkit has two groups of features outlined below (Sandboxing was removed in runkit7):

**Comment by TysonAndre** [comment]
Progress will be tracked in #114
