### ISSUE TITLE
Error when running make and make test on 16.04 (linux kernal 4.4), php 7.2.8

### ISSUE THREAD

**Issue by tspesh** [runkit7/runkit7#145]
Very confused.  Just ran this locally on my machine and it works great.  Trying to install on a digital ocean machine and it's failing (see below).  Both are running the same software.  

`/bin/bash /home/tim/Downloads/runkit7/libtool --mode=compile cc -Wdeclaration-after-statement -Werror -Wall -Wno-deprecated-declarations -Wno-pedantic -I. -I/home/tim/Downloads/runkit7 -DPHP_ATOM_INC -I/home/tim/Downloads/runkit7/include -I/home/tim/Downloads/runkit7/main -I/home/tim/Downloads/runkit7 -I/usr/include/php/20131226 -I/usr/include/php/20131226/main -I/usr/include/php/20131226/TSRM -I/usr/include/php/20131226/Zend -I/usr/include/php/20131226/ext -I/usr/include/php/20131226/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /home/tim/Downloads/runkit7/runkit.c -o runkit.lo 
libtool: compile:  cc -Wdeclaration-after-statement -Werror -Wall -Wno-deprecated-declarations -Wno-pedantic -I. -I/home/tim/Downloads/runkit7 -DPHP_ATOM_INC -I/home/tim/Downloads/runkit7/include -I/home/tim/Downloads/runkit7/main -I/home/tim/Downloads/runkit7 -I/usr/include/php/20131226 -I/usr/include/php/20131226/main -I/usr/include/php/20131226/TSRM -I/usr/include/php/20131226/Zend -I/usr/include/php/20131226/ext -I/usr/include/php/20131226/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /home/tim/Downloads/runkit7/runkit.c  -fPIC -DPIC -o .libs/runkit.o
In file included from /home/tim/Downloads/runkit7/runkit.c:24:0:
/home/tim/Downloads/runkit7/runkit.h:68:25: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 extern PHPAPI ZEND_COLD void php_error_docref(const char *docref, int type, const char *format, ...)
                         ^
In file included from /home/tim/Downloads/runkit7/runkit.c:24:0:
/home/tim/Downloads/runkit7/runkit.h:265:71: error: unknown type name ‘zend_string’
 static inline void *runkit_zend_hash_add_or_update_ptr(HashTable *ht, zend_string *key, void *pData, uint32_t flag)
                                                                       ^
/home/tim/Downloads/runkit7/runkit.h:290:47: error: unknown type name ‘zend_string’
 void php_runkit_fix_all_hardcoded_stack_sizes(zend_string *called_name_lower, zend_function *called_f);
                                               ^
/home/tim/Downloads/runkit7/runkit.h:294:61: error: unknown type name ‘zend_string’
 zend_function *php_runkit_function_clone(zend_function *fe, zend_string *newname, char orig_fe_type);
                                                             ^
/home/tim/Downloads/runkit7/runkit.h:296:70: error: unknown type name ‘zend_string’
 int php_runkit_remove_from_function_table(HashTable *function_table, zend_string *func_lower);
                                                                      ^
/home/tim/Downloads/runkit7/runkit.h:297:67: error: unknown type name ‘zend_string’
 void *php_runkit_update_function_table(HashTable *function_table, zend_string *func_lower, zend_function *f);
                                                                   ^
/home/tim/Downloads/runkit7/runkit.h:298:45: error: unknown type name ‘zend_string’
 int php_runkit_generate_lambda_method(const zend_string *arguments, const zend_string *return_type, const zend_bool is_strict, const zend_string *phpcode,
                                             ^
/home/tim/Downloads/runkit7/runkit.h:298:75: error: unknown type name ‘zend_string’
 int php_runkit_generate_lambda_method(const zend_string *arguments, const zend_string *return_type, const zend_bool is_strict, const zend_string *phpcode,
                                                                           ^
/home/tim/Downloads/runkit7/runkit.h:298:134: error: unknown type name ‘zend_string’
 int php_runkit_generate_lambda_method(const zend_string *arguments, const zend_string *return_type, const zend_bool is_strict, const zend_string *phpcode,
                                                                                                                                      ^
/home/tim/Downloads/runkit7/runkit.h:300:47: error: unknown type name ‘zend_string’
 int php_runkit_generate_lambda_function(const zend_string *arguments, const zend_string *return_type, const zend_bool is_strict, const zend_string *phpcode,
                                               ^
/home/tim/Downloads/runkit7/runkit.h:300:77: error: unknown type name ‘zend_string’
 int php_runkit_generate_lambda_function(const zend_string *arguments, const zend_string *return_type, const zend_bool is_strict, const zend_string *phpcode,
                                                                             ^
/home/tim/Downloads/runkit7/runkit.h:300:136: error: unknown type name ‘zend_string’
 int php_runkit_generate_lambda_function(const zend_string *arguments, const zend_string *return_type, const zend_bool is_strict, const zend_string *phpcode,
                                                                                                                                        ^
/home/tim/Downloads/runkit7/runkit.h:305:43: error: unknown type name ‘zend_string’
 void php_runkit_restore_internal_function(zend_string *fname_lower, zend_function *f);
                                           ^
/home/tim/Downloads/runkit7/runkit.h:308:42: error: unknown type name ‘zend_string’
 zend_class_entry *php_runkit_fetch_class(zend_string *classname);
                                          ^
/home/tim/Downloads/runkit7/runkit.h:309:46: error: unknown type name ‘zend_string’
 zend_class_entry *php_runkit_fetch_class_int(zend_string *classname);
                                              ^
/home/tim/Downloads/runkit7/runkit.h:310:128: error: unknown type name ‘zend_string’
 void php_runkit_clean_children_methods(zend_class_entry *ce, zend_class_entry *ancestor_class, zend_class_entry *parent_class, zend_string *fname_lower, zend_function *orig_cfe);
                                                                                                                                ^
/home/tim/Downloads/runkit7/runkit.h:311:129: error: unknown type name ‘zend_string’
 void php_runkit_clean_children_methods_foreach(HashTable *ht, zend_class_entry *ancestor_class, zend_class_entry *parent_class, zend_string *fname_lower, zend_function *orig_cfe);
                                                                                                                                 ^
/home/tim/Downloads/runkit7/runkit.h:312:148: error: unknown type name ‘zend_string’
 void php_runkit_update_children_methods(zend_class_entry *ce, zend_class_entry *ancestor_class, zend_class_entry *parent_class, zend_function *fe, zend_string *fname_lower, zend_function *orig_fe);
                                                                                                                                                    ^
/home/tim/Downloads/runkit7/runkit.h:313:149: error: unknown type name ‘zend_string’
 void php_runkit_update_children_methods_foreach(HashTable *ht, zend_class_entry *ancestor_class, zend_class_entry *parent_class, zend_function *fe, zend_string *fname_lower, zend_function *orig_fe);
                                                                                                                                                     ^
/home/tim/Downloads/runkit7/runkit.h:314:32: error: unknown type name ‘zend_string’
 int php_runkit_fetch_interface(zend_string *classname, zend_class_entry **pce);
                                ^
/home/tim/Downloads/runkit7/runkit.h:324:103: error: unknown type name ‘zend_string’
 void php_runkit_update_children_consts(zend_class_entry *ce, zend_class_entry *parent_class, zval *c, zend_string *cname RUNKIT_CONST_FLAGS_DC(access_type));
                                                                                                       ^
/home/tim/Downloads/runkit7/runkit.h:325:104: error: unknown type name ‘zend_string’
 void php_runkit_update_children_consts_foreach(HashTable *ht, zend_class_entry *parent_class, zval *c, zend_string *cname RUNKIT_CONST_FLAGS_DC(access_type));
                                                                                                        ^
/home/tim/Downloads/runkit7/runkit.h:328:50: error: unknown type name ‘zend_string’
 int php_runkit_class_copy(zend_class_entry *src, zend_string *classname);
                                                  ^
/home/tim/Downloads/runkit7/runkit.h:331:106: error: unknown type name ‘zend_string’
 void php_runkit_update_children_def_props(zend_class_entry *ce, zend_class_entry *parent_class, zval *p, zend_string *pname, int access_type, zend_class_entry *definer_class, int override, int override_in_object
                                                                                                          ^
/home/tim/Downloads/runkit7/runkit.h:332:55: error: unknown type name ‘zend_string’
 int php_runkit_def_prop_add_int(zend_class_entry *ce, zend_string *propname, zval *copyval, long visibility,
                                                       ^
/home/tim/Downloads/runkit7/runkit.h:333:5: error: unknown type name ‘zend_string’
     zend_string *doc_comment, zend_class_entry *definer_class, int override,
     ^
/home/tim/Downloads/runkit7/runkit.h:335:58: error: unknown type name ‘zend_string’
 int php_runkit_def_prop_remove_int(zend_class_entry *ce, zend_string *propname, zend_class_entry *definer_class,
                                                          ^
/home/tim/Downloads/runkit7/runkit.h:345:2: error: unknown type name ‘zend_string’
  zend_string *return_type;
  ^
/home/tim/Downloads/runkit7/runkit.h:384:78: error: unknown type name ‘zend_string’
 static inline void php_runkit_modify_function_doc_comment(zend_function *fe, zend_string *doc_comment)
                                                                              ^
/home/tim/Downloads/runkit7/runkit.h:506:56: error: unknown type name ‘zend_string’
 void PHP_RUNKIT_ADD_MAGIC_METHOD(zend_class_entry *ce, zend_string *lcmname, zend_function *fe, const zend_function *orig_fe);
                                                        ^
/home/tim/Downloads/runkit7/runkit.h:517:15: error: unknown type name ‘zend_string’
 inline static zend_string *php_runkit_parse_doc_comment_arg(int argc, zval *args, int arg_pos)
               ^
/home/tim/Downloads/runkit7/runkit.h: In function ‘php_runkit_parse_doc_comment_arg’:
/home/tim/Downloads/runkit7/runkit.h:522:11: error: implicit declaration of function ‘Z_STR’ [-Werror=implicit-function-declaration]
    return Z_STR(args[arg_pos]);
           ^
/home/tim/Downloads/runkit7/runkit.h:522:11: error: return makes pointer from integer without a cast [-Werror=int-conversion]
/home/tim/Downloads/runkit7/runkit.h: At top level:
/home/tim/Downloads/runkit7/runkit.h:532:63: error: unknown type name ‘zend_string’
 inline static zend_bool php_runkit_is_valid_return_type(const zend_string *return_type)
                                                               ^
/home/tim/Downloads/runkit7/runkit.h: In function ‘php_runkit_is_valid_return_type’:
/home/tim/Downloads/runkit7/runkit.h:534:19: error: implicit declaration of function ‘ZSTR_VAL’ [-Werror=implicit-function-declaration]
  const char *it = ZSTR_VAL(return_type);
                   ^
/home/tim/Downloads/runkit7/runkit.h:534:19: error: initialization makes pointer from integer without a cast [-Werror=int-conversion]
/home/tim/Downloads/runkit7/runkit.h:535:31: error: implicit declaration of function ‘ZSTR_LEN’ [-Werror=implicit-function-declaration]
  const char *const end = it + ZSTR_LEN(return_type);
                               ^
/home/tim/Downloads/runkit7/runkit.h: In function ‘php_runkit_parse_return_type_arg’:
/home/tim/Downloads/runkit7/runkit.h:592:3: error: unknown type name ‘zend_string’
   zend_string *return_type = Z_STR(args[arg_pos]);
   ^
/home/tim/Downloads/runkit7/runkit.h:592:30: error: initialization makes pointer from integer without a cast [-Werror=int-conversion]
   zend_string *return_type = Z_STR(args[arg_pos]);
                              ^
/home/tim/Downloads/runkit7/runkit.h: In function ‘php_runkit_parse_is_strict_arg’:
/home/tim/Downloads/runkit7/runkit.h:626:31: error: ‘IS_TRUE’ undeclared (first use in this function)
  if (Z_TYPE(args[arg_pos]) == IS_TRUE || Z_TYPE(args[arg_pos]) == IS_FALSE) {
                               ^
/home/tim/Downloads/runkit7/runkit.h:626:31: note: each undeclared identifier is reported only once for each function it appears in
/home/tim/Downloads/runkit7/runkit.h:626:67: error: ‘IS_FALSE’ undeclared (first use in this function)
  if (Z_TYPE(args[arg_pos]) == IS_TRUE || Z_TYPE(args[arg_pos]) == IS_FALSE) {
                                                                   ^
In file included from /usr/include/php/20131226/main/php.h:40:0,
                 from /home/tim/Downloads/runkit7/runkit.h:29,
                 from /home/tim/Downloads/runkit7/runkit.c:24:
/home/tim/Downloads/runkit7/runkit.h: In function ‘php_runkit_parse_args_to_zvals’:
/home/tim/Downloads/runkit7/runkit.h:647:41: error: passing argument 2 of ‘_zend_get_parameters_array_ex’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  if (zend_get_parameters_array_ex(argc, *pargs) == FAILURE) {
                                         ^
/usr/include/php/20131226/Zend/zend_API.h:250:45: note: in definition of macro ‘zend_get_parameters_array_ex’
  _zend_get_parameters_array_ex(param_count, argument_array TSRMLS_CC)
                                             ^
/usr/include/php/20131226/Zend/zend_API.h:242:14: note: expected ‘zval *** {aka struct _zval_struct ***}’ but argument is of type ‘zval * {aka struct _zval_struct *}’
 ZEND_API int _zend_get_parameters_array_ex(int param_count, zval ***argument_array TSRMLS_DC);
              ^
In file included from /home/tim/Downloads/runkit7/runkit.c:24:0:
/home/tim/Downloads/runkit7/runkit.h: At top level:
/home/tim/Downloads/runkit7/runkit.h:662:15: error: unknown type name ‘zend_string’
 inline static zend_string *zend_string_to_interned(zend_string *original)
               ^
/home/tim/Downloads/runkit7/runkit.h:662:52: error: unknown type name ‘zend_string’
 inline static zend_string *zend_string_to_interned(zend_string *original)
                                                    ^
/home/tim/Downloads/runkit7/runkit.h:674:110: error: unknown type name ‘zend_string’
 inline static zend_bool php_runkit_parse_function_arg(int argc, zval *args, int arg_pos, zend_function **fe, zend_string **arguments, zend_string **phpcode, long *opt_arg_pos, char *type)
                                                                                                              ^
/home/tim/Downloads/runkit7/runkit.h:674:135: error: unknown type name ‘zend_string’
 inline static zend_bool php_runkit_parse_function_arg(int argc, zval *args, int arg_pos, zend_function **fe, zend_string **arguments, zend_string **phpcode, long *opt_arg_pos, char *type)
                                                                                                                                       ^
/home/tim/Downloads/runkit7/runkit.c: In function ‘zif_runkit_superglobals’:
/home/tim/Downloads/runkit7/runkit.c:34:2: error: unknown type name ‘zend_string’
  zend_string *key;
  ^
/home/tim/Downloads/runkit7/runkit.c:37:2: error: implicit declaration of function ‘ZEND_HASH_FOREACH_STR_KEY’ [-Werror=implicit-function-declaration]
  ZEND_HASH_FOREACH_STR_KEY(CG(auto_globals), key) {
  ^
/home/tim/Downloads/runkit7/runkit.c:37:51: error: expected ‘;’ before ‘{’ token
  ZEND_HASH_FOREACH_STR_KEY(CG(auto_globals), key) {
                                                   ^
/home/tim/Downloads/runkit7/runkit.c: In function ‘zif_runkit_zval_inspect’:
/home/tim/Downloads/runkit7/runkit.c:63:59: error: macro "add_assoc_stringl" requires 5 arguments, but only 4 given
  add_assoc_stringl(return_value, "address", addr, addr_len);
                                                           ^
/home/tim/Downloads/runkit7/runkit.c:63:2: error: ‘add_assoc_stringl’ undeclared (first use in this function)
  add_assoc_stringl(return_value, "address", addr, addr_len);
  ^
/home/tim/Downloads/runkit7/runkit.c:67:6: error: implicit declaration of function ‘Z_REFCOUNTED_P’ [-Werror=implicit-function-declaration]
  if (Z_REFCOUNTED_P(value)) {
      ^
/home/tim/Downloads/runkit7/runkit.c:54:6: error: variable ‘addr_len’ set but not used [-Werror=unused-but-set-variable]
  int addr_len;
      ^
/home/tim/Downloads/runkit7/runkit.c: In function ‘_php_runkit_init_stub_function’:
/home/tim/Downloads/runkit7/runkit.c:309:36: error: implicit declaration of function ‘zend_string_init’ [-Werror=implicit-function-declaration]
  (*result)->common.function_name = zend_string_init(name, strlen(name), 1);  // TODO: Can this be persistent?
                                    ^
/home/tim/Downloads/runkit7/runkit.c:309:34: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
  (*result)->common.function_name = zend_string_init(name, strlen(name), 1);  // TODO: Can this be persistent?
                                  ^
/home/tim/Downloads/runkit7/runkit.c: In function ‘_php_runkit_feature_constant’:
/home/tim/Downloads/runkit7/runkit.c:353:9: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
  c.name = zend_string_init(name, name_len - 1, 1);  // TODO: can this be persistent?
         ^
/home/tim/Downloads/runkit7/runkit.c: In function ‘php_runkit_register_auto_global’:
/home/tim/Downloads/runkit7/runkit.c:454:2: error: unknown type name ‘zend_string’
  zend_string *globalName = zend_string_init(s, len, 1);
  ^
/home/tim/Downloads/runkit7/runkit.c:454:28: error: initialization makes pointer from integer without a cast [-Werror=int-conversion]
  zend_string *globalName = zend_string_init(s, len, 1);
                            ^
/home/tim/Downloads/runkit7/runkit.c:457:41: error: passing argument 2 of ‘zend_hash_exists’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  if (zend_hash_exists(CG(auto_globals), globalName)) {
                                         ^
In file included from /usr/include/php/20131226/Zend/zend.h:286:0,
                 from /usr/include/php/20131226/main/php.h:36,
                 from /home/tim/Downloads/runkit7/runkit.h:29,
                 from /home/tim/Downloads/runkit7/runkit.c:24:
/usr/include/php/20131226/Zend/zend_hash.h:169:14: note: expected ‘const char *’ but argument is of type ‘int *’
 ZEND_API int zend_hash_exists(const HashTable *ht, const char *arKey, uint nKeyLength);
              ^
/home/tim/Downloads/runkit7/runkit.c:457:6: error: too few arguments to function ‘zend_hash_exists’
  if (zend_hash_exists(CG(auto_globals), globalName)) {
      ^
In file included from /usr/include/php/20131226/Zend/zend.h:286:0,
                 from /usr/include/php/20131226/main/php.h:36,
                 from /home/tim/Downloads/runkit7/runkit.h:29,
                 from /home/tim/Downloads/runkit7/runkit.c:24:
/usr/include/php/20131226/Zend/zend_hash.h:169:14: note: declared here
 ZEND_API int zend_hash_exists(const HashTable *ht, const char *arKey, uint nKeyLength);
              ^
/home/tim/Downloads/runkit7/runkit.c:459:3: error: implicit declaration of function ‘zend_string_release’ [-Werror=implicit-function-declaration]
   zend_string_release(globalName);
   ^
/home/tim/Downloads/runkit7/runkit.c:463:32: error: passing argument 1 of ‘zend_register_auto_global’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  if (zend_register_auto_global(globalName,
                                ^
In file included from /usr/include/php/20131226/Zend/zend_modules.h:26:0,
                 from /usr/include/php/20131226/Zend/zend_API.h:26,
                 from /usr/include/php/20131226/main/php.h:40,
                 from /home/tim/Downloads/runkit7/runkit.h:29,
                 from /home/tim/Downloads/runkit7/runkit.c:24:
/usr/include/php/20131226/Zend/zend_compile.h:729:14: note: expected ‘const char *’ but argument is of type ‘int *’
 ZEND_API int zend_register_auto_global(const char *name, uint name_len, zend_bool jit, zend_auto_global_callback auto_global_callback TSRMLS_DC);
              ^
/home/tim/Downloads/runkit7/runkit.c:465:7: error: passing argument 3 of ‘zend_register_auto_global’ makes integer from pointer without a cast [-Werror=int-conversion]
       NULL) == SUCCESS) {
       ^
In file included from /usr/include/php/20131226/Zend/zend_modules.h:26:0,
                 from /usr/include/php/20131226/Zend/zend_API.h:26,
                 from /usr/include/php/20131226/main/php.h:40,
                 from /home/tim/Downloads/runkit7/runkit.h:29,
                 from /home/tim/Downloads/runkit7/runkit.c:24:
/usr/include/php/20131226/Zend/zend_compile.h:729:14: note: expected ‘zend_bool {aka unsigned char}’ but argument is of type ‘void *’
 ZEND_API int zend_register_auto_global(const char *name, uint name_len, zend_bool jit, zend_auto_global_callback auto_global_callback TSRMLS_DC);
              ^
/home/tim/Downloads/runkit7/runkit.c:463:6: error: too few arguments to function ‘zend_register_auto_global’
  if (zend_register_auto_global(globalName,
      ^
In file included from /usr/include/php/20131226/Zend/zend_modules.h:26:0,
                 from /usr/include/php/20131226/Zend/zend_API.h:26,
                 from /usr/include/php/20131226/main/php.h:40,
                 from /home/tim/Downloads/runkit7/runkit.h:29,
                 from /home/tim/Downloads/runkit7/runkit.c:24:
/usr/include/php/20131226/Zend/zend_compile.h:729:14: note: declared here
 ZEND_API int zend_register_auto_global(const char *name, uint name_len, zend_bool jit, zend_auto_global_callback auto_global_callback TSRMLS_DC);
              ^
/home/tim/Downloads/runkit7/runkit.c:469:22: error: implicit declaration of function ‘zend_hash_find_ptr’ [-Werror=implicit-function-declaration]
   if ((auto_global = zend_hash_find_ptr(CG(auto_globals), globalName)) == NULL) {
                      ^
/home/tim/Downloads/runkit7/runkit.c:469:20: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
   if ((auto_global = zend_hash_find_ptr(CG(auto_globals), globalName)) == NULL) {
                    ^
/home/tim/Downloads/runkit7/runkit.c:482:3: error: implicit declaration of function ‘ZVAL_NEW_STR’ [-Werror=implicit-function-declaration]
   ZVAL_NEW_STR(&z, zend_string_init(s, len, 1));
   ^
/home/tim/Downloads/runkit7/runkit.c:483:57: error: macro "zend_hash_next_index_insert" requires 4 arguments, but only 2 given
   zend_hash_next_index_insert(RUNKIT_G(superglobals), &z);
                                                         ^
/home/tim/Downloads/runkit7/runkit.c:483:3: error: ‘zend_hash_next_index_insert’ undeclared (first use in this function)
   zend_hash_next_index_insert(RUNKIT_G(superglobals), &z);
   ^
/home/tim/Downloads/runkit7/runkit.c: In function ‘php_runkit_superglobal_dtor’:
/home/tim/Downloads/runkit7/runkit.c:549:45: error: macro "zend_hash_del" requires 3 arguments, but only 2 given
  zend_hash_del(CG(auto_globals), Z_STR_P(zv));
                                             ^
/home/tim/Downloads/runkit7/runkit.c:549:2: error: ‘zend_hash_del’ undeclared (first use in this function)
  zend_hash_del(CG(auto_globals), Z_STR_P(zv));
  ^
/home/tim/Downloads/runkit7/runkit.c: In function ‘zm_deactivate_runkit’:
/home/tim/Downloads/runkit7/runkit.c:566:43: error: passing argument 2 of ‘zend_hash_apply’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   zend_hash_apply(RUNKIT_G(superglobals), php_runkit_superglobal_dtor);
                                           ^
In file included from /usr/include/php/20131226/Zend/zend.h:286:0,
                 from /usr/include/php/20131226/main/php.h:36,
                 from /home/tim/Downloads/runkit7/runkit.h:29,
                 from /home/tim/Downloads/runkit7/runkit.c:24:
/usr/include/php/20131226/Zend/zend_hash.h:139:15: note: expected ‘apply_func_t {aka int (*)(void *)}’ but argument is of type ‘int (*)(zval *) {aka int (*)(struct _zval_struct *)}’
 ZEND_API void zend_hash_apply(HashTable *ht, apply_func_t apply_func TSRMLS_DC);
               ^
/home/tim/Downloads/runkit7/runkit.c:576:59: error: passing argument 2 of ‘zend_hash_apply’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   zend_hash_apply(RUNKIT_G(misplaced_internal_functions), php_runkit_destroy_misplaced_functions);
                                                           ^
In file included from /usr/include/php/20131226/Zend/zend.h:286:0,
                 from /usr/include/php/20131226/main/php.h:36,
                 from /home/tim/Downloads/runkit7/runkit.h:29,
                 from /home/tim/Downloads/runkit7/runkit.c:24:
/usr/include/php/20131226/Zend/zend_hash.h:139:15: note: expected ‘apply_func_t {aka int (*)(void *)}’ but argument is of type ‘int (*)(zval *) {aka int (*)(struct _zval_struct *)}’
 ZEND_API void zend_hash_apply(HashTable *ht, apply_func_t apply_func TSRMLS_DC);
               ^
/home/tim/Downloads/runkit7/runkit.c:589:3: error: unknown type name ‘zend_string’
   zend_string *key;
   ^
/home/tim/Downloads/runkit7/runkit.c:591:3: error: implicit declaration of function ‘ZEND_HASH_FOREACH_STR_KEY_PTR’ [-Werror=implicit-function-declaration]
   ZEND_HASH_FOREACH_STR_KEY_PTR(RUNKIT_G(replaced_internal_functions), key, f) {
   ^
/home/tim/Downloads/runkit7/runkit.c:591:80: error: expected ‘;’ before ‘{’ token
   ZEND_HASH_FOREACH_STR_KEY_PTR(RUNKIT_G(replaced_internal_functions), key, f) {
`

**Comment by TysonAndre** [comment]
You're using phpize from php 5.6, or pecl from php5.6, so you're getting the `/usr/include/php/20131226` from 2013-12-26 (i.e. that is the module date used by php 5.6).

If you instead run `/path/to/php7.2/bin/phpize; ./configure; make clean; make` (or the equivalent), then that should work properly)

**Comment by TysonAndre** [comment]
Also, make sure that `/path/to/php7.2/bin:` is the first thing in your `PATH` environment variable, before /usr/bin, and anywhere else php installations would bec.

**Comment by tspesh** [comment]
You're a saint.  Updated and it works now thanks.
