### ISSUE TITLE
Help with compile error for PHP 7.1 on Windows: #error:  DEBUG - RUNKIT_FEATURE_MODIFY DISABLED

### ISSUE THREAD

**Issue by egifford** [runkit7/runkit7#164]
Hi Runkit7,

This is great extension. Thanks for porting it to PHP7.

I've successfully compiled version 1.04 in the past, but I'm running into an issue compiling version 1.0.9 for PHP version 7.1.27 with PHP-SDK 2.1.10 on VC14 on Windows 10.

The output of nmake is below. I'm assuming I'm messing something up and I'm hoping someone has a quick "just do this" pointer.  If not, I can provide more information and tool output.

Any help is appreciated. Thanks!

> Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> Recreating build dirs
> Recreating build dirs
        type ext\pcre\php_pcre.def > C:\Work\projects\php-sdk-7.1.27\phpdev\vc14\x64\php-7.1.27-src\x64\Release_TS\php7ts.dll.def
        "cl.exe" /D COMPILE_DL_RUNKIT /D RUNKIT_EXPORTS=1 /nologo /I . /I main /I Zend /I TSRM /I ext /D _WINDOWS /D ZEND_WIN32=1 /D PHP_WIN32=1 /D WIN32 /D _MBCS /W3 /FD /wd4996 /Zc:inline /MP /LD /MD /W3 /Ox /D NDebug /D NDEBUG /D ZEND_WIN32_FORCE_INLINE /GF /D ZEND_DEBUG=0 /D ZTS=1 /I "C:\Work\projects\php-sdk-7.1.27\phpdev\vc14\x64\deps\include" /D FD_SETSIZE=256 /FoC:\Work\projects\php-sdk-7.1.27\phpdev\vc14\x64\php-7.1.27-src\x64\Release_TS\pecl\runkit7\ /FpC:\Work\projects\php-sdk-7.1.27\phpdev\vc14\x64\php-7.1.27-src\x64\Release_TS\pecl\runkit7\ /FRC:\Work\projects\php-sdk-7.1.27\phpdev\vc14\x64\php-7.1.27-src\x64\Release_TS\pecl\runkit7\ /FdC:\Work\projects\php-sdk-7.1.27\phpdev\vc14\x64\php-7.1.27-src\x64\Release_TS\pecl\runkit7\ /c ..\pecl\runkit7\runkit.c ..\pecl\runkit7\runkit_classes.c ..\pecl\runkit7\runkit_common.c ..\pecl\runkit7\runkit_constants.c ..\pecl\runkit7\runkit_functions.c ..\pecl\runkit7\runkit_import.c ..\pecl\runkit7\runkit_methods.c ..\pecl\runkit7\runkit_object_id.c ..\pecl\runkit7\runkit_props.c ..\pecl\runkit7\runkit_zend_execute_API.c
runkit.c
runkit_classes.c
runkit_common.c
runkit_constants.c
runkit_functions.c
runkit_import.c
runkit_methods.c
runkit_object_id.c
c:\work\projects\php-sdk-7.1.27\phpdev\vc14\x64\pecl\runkit7\runkit.h(133): fatal error C1189: #error:  DEBUG - RUNKIT_FEATURE_MODIFY DISABLED (compiling source file ..\pecl\runkit7\runkit_common.c)
c:\work\projects\php-sdk-7.1.27\phpdev\vc14\x64\pecl\runkit7\runkit.h(133): fatal error C1189: #error:  DEBUG - RUNKIT_FEATURE_MODIFY DISABLED (compiling source file ..\pecl\runkit7\runkit_classes.c)
c:\work\projects\php-sdk-7.1.27\phpdev\vc14\x64\pecl\runkit7\runkit.h(133): fatal error C1189: #error:  DEBUG - RUNKIT_FEATURE_MODIFY DISABLED (compiling source file ..\pecl\runkit7\runkit_constants.c)
c:\work\projects\php-sdk-7.1.27\phpdev\vc14\x64\pecl\runkit7\runkit.h(133): fatal error C1189: #error:  DEBUG - RUNKIT_FEATURE_MODIFY DISABLED (compiling source file ..\pecl\runkit7\runkit_object_id.c)
c:\work\projects\php-sdk-7.1.27\phpdev\vc14\x64\pecl\runkit7\runkit.h(133): fatal error C1189: #error:  DEBUG - RUNKIT_FEATURE_MODIFY DISABLED (compiling source file ..\pecl\runkit7\runkit_import.c)
c:\work\projects\php-sdk-7.1.27\phpdev\vc14\x64\pecl\runkit7\runkit.h(133): fatal error C1189: #error:  DEBUG - RUNKIT_FEATURE_MODIFY DISABLED (compiling source file ..\pecl\runkit7\runkit.c)
c:\work\projects\php-sdk-7.1.27\phpdev\vc14\x64\pecl\runkit7\runkit.h(133): fatal error C1189: #error:  DEBUG - RUNKIT_FEATURE_MODIFY DISABLED (compiling source file ..\pecl\runkit7\runkit_functions.c)
runkit_props.c
runkit_zend_execute_API.c
c:\work\projects\php-sdk-7.1.27\phpdev\vc14\x64\pecl\runkit7\runkit.h(133): fatal error C1189: #error:  DEBUG - RUNKIT_FEATURE_MODIFY DISABLED (compiling source file ..\pecl\runkit7\runkit_methods.c)
c:\work\projects\php-sdk-7.1.27\phpdev\vc14\x64\pecl\runkit7\runkit.h(133): fatal error C1189: #error:  DEBUG - RUNKIT_FEATURE_MODIFY DISABLED (compiling source file ..\pecl\runkit7\runkit_props.c)
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe"' : return code '0x2'
Stop.

**Comment by TysonAndre** [comment]
This should be fixed with https://github.com/runkit7/runkit7/pull/165 (fixes branch)

Adding the flag --runkit-modify (./configure --help) should fix builds on Windows, I think. Haven't tested that out yet.

**Comment by egifford** [comment]
Thanks for the really quick response.  Your change made a default compile work.

Also, your suggestion to add --enable-runkit-modify got me working for version 1.0.9.  We're using runkit_method_redefine() so I needed to know about the flag!

Thanks!
