### ISSUE TITLE
StaticMock doesn't work PHP7.3 

### ISSUE THREAD

**Issue by dmnlk** [runkit7/runkit7#172]
I issued to StaticMock.
https://github.com/tototoshi/staticmock/issues/10

StaticMock that uses runkit7 doesn't work on PHP 7.3 environment.
StaticMock uses `runkit_method_add`, `runkit_method_rename`, `runkit_method_rename`, `runkit_method_remove`  in runkit methods.
any idea?

**Comment by TysonAndre** [comment]
I'm able to reproduce this in NTS and debug builds. It'd help if this could be simplified to a single file test case not using a framework.

It's probably runkit7, but could be a language change (much less likely)

**Comment by dmnlk** [comment]
@TysonAndre thanks!StaticMock works on 7.3!
