### ISSUE TITLE
Unable to compile runkit7 when building with different compiler version than used to build php

### ISSUE THREAD

**Issue by NotSmilie** [runkit7/runkit7#219]
Hi,
I'm on php 7.2 and I ran the following command: pecl install runkit7-alpha

`downloading runkit7-3.1.0a1.tgz ...
Starting to download runkit7-3.1.0a1.tgz (121,777 bytes)
..........................done: 121,777 bytes
18 source files, building
running: phpize
Configuring for:
PHP Api Version:         20170718
Zend Module Api No:      20170718
Zend Extension Api No:   320170718
building in /var/tmp/pear-build-rootdc7du9/runkit7-3.1.0a1
running: /var/tmp/runkit7/configure --with-php-config=/usr/bin/php-config
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib
checking for PHP extension directory... /usr/lib64/php/modules
checking for PHP installed headers prefix... /usr/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking whether to enable runkit7 support... yes, shared
checking whether to enable runtime manipulation of functions/classes/constants... inherit
checking whether to enable registration of user-defined autoglobals... yes, shared
checking whether to enable spl_object_id in PHP <= 7.1... no
checking if this is built with PHP >= 7.1... this is PHP 7.1 or newer
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... (cached) gawk
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC -DPIC
checking if cc PIC flag -fPIC -DPIC works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
configure: creating ./config.status
config.status: creating config.h
config.status: executing libtool commands
running: make
/bin/sh /var/tmp/pear-build-rootdc7du9/runkit7-3.1.0a1/libtool --mode=compile cc -Wdeclaration-after-statement -Werror -Wall -Wno-deprecated-declarations -Wno-pedantic -I. -I/var/tmp/runkit7 -DPHP_ATOM_INC -I/var/tmp/pear-build-rootdc7du9/runkit7-3.1.0a1/include -I/var/tmp/pear-build-rootdc7du9/runkit7-3.1.0a1/main -I/var/tmp/runkit7 -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /var/tmp/runkit7/runkit.c -o runkit.lo
libtool: compile:  cc -Wdeclaration-after-statement -Werror -Wall -Wno-deprecated-declarations -Wno-pedantic -I. -I/var/tmp/runkit7 -DPHP_ATOM_INC -I/var/tmp/pear-build-rootdc7du9/runkit7-3.1.0a1/include -I/var/tmp/pear-build-rootdc7du9/runkit7-3.1.0a1/main -I/var/tmp/runkit7 -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /var/tmp/runkit7/runkit.c  -fPIC -DPIC -o .libs/runkit.o
In file included from /usr/include/php/Zend/zend.h:328:0,
                 from /usr/include/php/main/php.h:35,
                 from /var/tmp/runkit7/runkit.h:27,
                 from /var/tmp/runkit7/runkit.c:20:
/usr/include/php/Zend/zend_operators.h: In function 'fast_long_increment_function':
/usr/include/php/Zend/zend_operators.h:446:2: error: implicit declaration of function '__builtin_saddl_overflow' [-Werror=implicit-function-declaration]
  if (UNEXPECTED(__builtin_saddl_overflow(Z_LVAL_P(op1), 1, &lresult))) {
  ^
/usr/include/php/Zend/zend_operators.h: In function 'fast_long_decrement_function':
/usr/include/php/Zend/zend_operators.h:500:2: error: implicit declaration of function '__builtin_ssubl_overflow' [-Werror=implicit-function-declaration]
  if (UNEXPECTED(__builtin_ssubl_overflow(Z_LVAL_P(op1), 1, &lresult))) {
  ^
cc1: all warnings being treated as errors
make: *** [runkit.lo] Error 1

Warning: chdir(): No such file or directory (errno 2) in PEAR/Builder.php on line 396
PHP Warning:  chdir(): No such file or directory (errno 2) in /usr/share/pear/PEAR/Builder.php on line 396
ERROR: `make' failed
`

**Comment by TysonAndre** [comment]
This is a known issue common to **all PECL extensions** when you use a different compiler version (e.g. clang instead of gcc, a much older version of gcc) than the compiler used to built php itself.

https://github.com/php/php-src/blob/php-7.2.29/Zend/zend_operators.h#L442-L460

PHP_HAVE_BUILTIN_SADDL_OVERFLOW and PHP_HAVE_BUILTIN_SADDLL_OVERFLOW (etc) are defined by php-src's `./configure` script, and are based on the capabilities of the **compiler used to build php-src** (e.g. whatever the package maintainer used). You're using an older or different compiler that doesn't support those capabilities to **build runkit7**.

/usr/include/php/main/php_config.h is a dynamically generated file in php's installation directory.

**Comment by TysonAndre** [comment]
Possible Solutions:

1. Update/switch your compiler (recommended if your OS provides a newer one than the one you're using). gcc is probably recommended, not sure what OS you're using (Linux? Mac?)
2. Manually edit /usr/include/php/main/php_config.h until the runkit7 build works (hackish, may mask other issues). Make sure to run `make test` of runkit7 after building

**Comment by TysonAndre** [comment]
Closing because /usr/include/php/Zend/zend_operators.h isn't a part of runkit7, and there are a large number of potential issues that could result from using a different compiler from what was used to build php-src.

**Comment by NotSmilie** [comment]
@TysonAndre I installed package from here https://centos.pkgs.org/7/remi-x86_64/php72-php-pecl-runkit7-2.1.0-1.el7.remi.x86_64.rpm.html instead

But I don't really see anything in phpinfo, in the extension dir, nor is the runkit7_function_redefine(); defined.
Any tips on where to start?

**Comment by TysonAndre** [comment]
You need to enable `extension=/opt/remi/php72/root/usr/lib64/php/modules/runkit7.so` in your php.ini.

**Comment by TysonAndre** [comment]
/etc/opt/remi/php72/php.d/ would have the ini settings, but I'm assuming the php72 package you have wasn't from remi's repo, so it wouldn't read that.

/usr/include/php is an entirely different php72 installation. You probably want to change /etc/php.ini (or add a file in /etc/php.d, if it exists)instead

**Comment by NotSmilie** [comment]
Thank you so much for your help, managed to get it working now :)
