### ISSUE TITLE
"The specified procedure could not be found" seen in Apache on Windows

### ISSUE THREAD

**Issue by batata004** [runkit7/runkit7#237]
I downloaded the `php_runkit7.dll` file (thread safe 64 bits) and placed on my `ext` directory. After that I changed `php.ini` and added the line:

    extension=php_runkit7

But when I start apache it says:

    PHP Warning:  PHP Startup: Unable to load dynamic library 'Z:\\servidor\\PHP\\ext\\php_runkit7' (tried: Z:\\servidor\\PHP\\ext\\php_runkit7 (The specified procedure could not be found.), Z:/servidor/PHP/ext\\php_Z:\\servidor\\PHP\\ext\\php_runkit7.dll (The specified module could not be found.)) in Unknown on line 0

So how do I fix this?

**Comment by TysonAndre** [comment]
I think that should either be `extension=php_runkit7.dll` or (in php7.4+ or so, optionally `extension=runkit7`. I forget if php_runkit7 would work

You should also check that you're using the dll for the same minor version. What php minor version(x.y) is that?

I haven't seen your issue before - it's possible that the runkit7 dll depends on versions of dlls that are different when it's run with apache -  https://superuser.com/questions/1201346/apache-and-php-curl-issue

What happens when you run `php -a` (CLI) - do you see the same error, do the functions from runkit7 exist?

**Comment by TysonAndre** [comment]
https://bugs.php.net/bug.php?id=76191 may be related.

Have you followed all of the steps in https://www.php.net/manual/en/install.windows.requirements.php and installed all of the dependencies (e.g. VC CRT)

Have you successfully installed and enabled any other PECL extensions?

**Comment by batata004** [comment]
I dont know why you pointed me at https://www.php.net/manual/en/install.windows.requirements.php since my LAMP stack is of course working properly. It just does not work when I add runkit7 in php.ini. Or should I do anything else besides copying the DLL and updating php.ini?

**Comment by batata004** [comment]
Hey guys I appreciate all your kindness helping me! So I come here to answer you: my PHP version is PHP Version 7.4.9 and I downloaded the file `php_runkit7.dll` from a person in a website (I cant find the website) where he said the had compiled the lastest version on May/2020. I also already tried setting the extension on `php.ini` with these 3 different lines (I tried one at a time, of course :) ) and also the absolute path, and it never works.

extension=php_runkit7
extension=php_runkit7.dll
extension=php_runkit7.so

Everytime I start apache it says: "PHP Warning:  PHP Startup: Unable to load dynamic library 'php_runkit7' (tried: Z:/servidor/PHP/ext\\php_runkit7 (The specified procedure could not be found.), Z:/servidor/PHP/ext\\php_php_runkit7.dll (The specified module could not be found.)) in Unknown on line 0"

I really need to use this awesome extension in order to circunvent a bug that I already reported to PHP.net but they say it's gonna take time to fix. I really need to remove function declaration, and this extension is awesome because is the only one I can find that does that!

Thank you so much for your attention, and keep the good work!

**Comment by TysonAndre** [comment]
>  and I downloaded the file php_runkit7.dll from a person in a website (I cant find the website) where he said the had compiled the lastest version on May/2020

The only recommended source of dlls for runkit7 are http://pecl.php.net/runkit7 (e.g. https://pecl.php.net/package/runkit7/3.1.0a1/windows) or building from source yourself using the instructions in https://github.com/runkit7/runkit7#building-and-installing-runkit7-in-windows (a bit outdated). I don't recommend downloading it from unknown sites

**Comment by batata004** [comment]
My dear friend, I was being stupid enough to download the dll from another source! I was not aware of the link nicely provided me on last message!

I went on your link and downloaded "7.4 Thread Safe (TS) x64" and extract the DLL on "C:\servidor\PHP\ext" (this direcotry is correct because I load curl from this same directory). And the error persists. Do I need to extract the other files somewhere else? The zip file has 7 files, should I extract them somewhere?

Answering your question, I executed the command you told me, the output is below: 

C:\Windows\system32>Z:\servidor\PHP\php.exe -a
PHP Warning:  PHP Startup: Unable to load dynamic library 'php_runkit7.so' (tried: Z:/servidor/PHP/ext\php_runkit7.so (The specified module could not be found.), Z:/servidor/PHP/ext\php_php_runkit7.so.dll (The specified module could not be found.)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'php_runkit7.so' (tried: Z:/servidor/PHP/ext\php_runkit7.so (The specified module could not be found.), Z:/servidor/PHP/ext\php_php_runkit7.so.dll (The specified module could not be found.)) in Unknown on line 0
Interactive shell

php >

**Comment by TysonAndre** [comment]
You're on windows. You should be using php_runkit7.dll (Windows DLL), not php_runkit7.so (Mac OS/Unix/Linux)

**Comment by TysonAndre** [comment]
>  Do I need to extract the other files somewhere else? The zip file has 7 files, should I extract them somewhere?

No, you just need the 1 dll. Refer to the documentation for https://www.php.net/manual/en/install.pecl.windows.php for more details, it's been a while since I looked at that or used Windows

**Comment by batata004** [comment]
UHULLLL I FINALLY INSTALLED!!! It works pretty amazing!!! Now my memory usabe is down by 90%!

I just found one small problem.  This code below, at every loop sets a function and removes it. However if I watch my memory usage while this code is being executed, it always goes up, never goes down. I even used `gc_mem_caches()` to make the garbage colector clear the memory at every loop, but it had no effect. Do you have any idea how can I prevent memory usage from going up when setting a function and unseting it?

I am not complaining about this extension, because without it the code below would end up eating all my ram in a matter of seconds! This exetension DOES provide a huge memory saving, but for some reason it's still using more and more RAM at every interaction of the loop below. Any idea?

for ($j=0;$j<1000000;$j++) {

	eval(' 
	
		$yyy = function ($a,$b,$c) {
		
			return $a . "' . $j . '" . $b . $c;
			
		};
		
	');

}

**Comment by batata004** [comment]
UHULLLL I FINALLY INSTALLED!!! It works pretty amazing!!! Now my memory usabe is down by 90%!

I just found one small problem. This code below, at every loop sets a function and removes it. However if I watch my memory usage while this code is being executed, it always goes up, never goes down. I even used gc_mem_caches() to make the garbage colector clear the memory at every loop, but it had no effect. Do you have any idea how can I prevent memory usage from going up when setting a function and unseting it?

I am not complaining about this extension, because without it the code below would end up eating all my ram in a matter of seconds! This exetension DOES provide a huge memory saving, but for some reason it's still using more and more RAM at every interaction of the loop below. Any idea?

```

for ($j=0;$j<1000000;$j++) {

	eval(' 
	
		function xxx($a,$b,$c) {
		
			return $a . "' . $j . '" . $b . $c;
			
		}
		
	');

	runkit7_function_remove("xxx");
	
}
```

And one final question. Is it possible to remove functions created anonymously? Like below? I tried many things and I could never clear it! I cant use `unset($xxx)` because GC will not clear the function if it is created using eval, which I am using to create the function below on my project.

```
$xxx = function($a,$b) {

   //do stuff

}
```

**Comment by TysonAndre** [comment]
> I just found one small problem. This code below, at every loop sets a function and removes it. However if I watch my memory usage while this code is being executed, it always goes up, never goes down. I even used gc_mem_caches() to make the garbage colector clear the memory at every loop, but it had no effect. **Do you have any idea how can I prevent memory usage from going up when setting a function and unseting it?**

This is documented in https://github.com/runkit7/runkit7#compatibility-php72-to-php-74

Despite my best effort to look into how to fix the leak, I ran into situations where the alternatives were to either have the potential for an application to crash or to slowly leak memory - manipulating the internals of the PHP VM is difficult, and errors can be hard to reproduce or identify the real cause of even with valgrind.
My main focus for runkit7 was on making it work for unit testing.

**The apache setting MaxConnectionsPerChild may help you with memory leaks if you are running out of memory - by reducing it, you can mitigate the impact of the memory leaks https://httpd.apache.org/docs/2.4/mod/mpm_common.html#maxconnectionsperchild .** (by default, it seems to be unlimited - you probably want to change that)

Sections from the README at https://github.com/runkit7/runkit7

> - Manipulating user-defined (i.e. not builtin or part of extensions) functions and methods via `runkit7_method_*` and `runkit7_function_*` generally works, **but is recommended only in unit tests** (unlikely to crash, but will cause memory leaks)
>
> ...
>
> -   There are reference counting bugs causing memory leaks.
>    2 calls to `emalloc` have been temporarily replaced with calls to `pemalloc`
>    so that tests would not crash during shutdown (and other reasons)

https://github.com/runkit7/runkit7#compatibility-php72-to-php-74

> Is it possible to remove functions created anonymously? Like below? 

Not through runkit's APIs, and doing so may cause its own set of problems - it would be difficult to tell if a closure definition could still be constructed and not a common enough use case to support in runkit7

(e.g. `function f12345() { return function($a, $b) {}}` would misbehave if the closure's implementation was removed but f12345 was still callable)

--------

An alternative approach you may wish to consider is to run the php 8.0.0rc1+ builds from https://windows.php.net/qa - Although running qa builds is not recommended in production, it may be more reliable to use php 8.0+ the ini setting disable_functions (which was refactored to actually allow redeclaring the function in 8.0) than to use runkit7+ php 8.0 in a web server. (The set of potential issues with the two approaches differ and have some unknowns)

**Comment by TysonAndre** [comment]
>  I even used gc_mem_caches() to make the garbage colector clear the memory at every loop, but it had no effect. Do you have any idea how can I prevent memory usage from going up when setting a function and unseting it?

To clarify the earlier comment:

To avoid the crashes that were too difficult to track down or be certain all cases were solved, this deliberately uses persistent allocations with memory not managed by php's garbage collection (`malloc`), not the memory managed by php (`emalloc`)

**Comment by TysonAndre** [comment]
On an unrelated note, https://pecl.php.net/runkit7 4.0.0a1 is out - it removes runkit7_import, and deprecates the runkit_* aliases for functions/constants in favor of runkit7_* to avoid confusion due to different signatures from the php 5 project and make documentation easier to find.

I'd been wondering if there'd be any way to fix runkit7_import, but that seems very unlikely, and it's been over half a year since the last official PECL release, so I decided to go ahead with the plans for 4.0.

**Comment by batata004** [comment]
Wow my friend, I feel ashamed for not reading or for not fully understanding the documentation. Everything you said was precisely referenced by a link. I should have read it all before come here taking your time.

Anyway, your explanations were really good. And the really small memory leak that is happening when using `runkit7_function_remove` is totally acceptable. I can restart apache once every day to make sure memory is restored.

Just one thing that I think that wont help me is decreasing the `MaxConnectionsPerChild` because I dont have users accessing my server. I am just processing a really CPU intensive AI code that I migrated from Python because it was running pretty slow there. PHP 7 gave a huge boost BUT the memory problem was holding me back. Now with your exntesion, I finally can move on with my project entirely with PHP7.

Thanks for clarifying about GC and about anonymous function.

And one final question (If I may use a little more of your time) on my project I basically do this (oversimplified):

```
	for ($i=0;$i<10000;++$) {

		eval('function hello($a,$b...) {return something;}');

		$world = hello($a,$b...);

		runkit7_function_remove('hello');

	}
```

For some strange reason the code above run faster (around 30%) than running the code below:

```
	for ($i=0;$i<10000;++$) {

		runkit7_function_redefine('hello','$a,$b...','return something;');
	
		$world = hello($a,$b...);

	}
```

The first code also runs almost 40% faster than code below:

```
	for ($i=0;$i<10000;++$) {

		runkit7_function_add('hello','$a,$b...','return something;');

		$world = hello($a,$b...);

		runkit7_function_remove('hello');

	}
```

IMHO, `runkit7_function_add` is clearly much slower than `eval`. So I think that you guys could tell users not to use that function and instead use `eval` directly to create functions since it's clearly faster and already highly optimized by PHP. What really amazes me is that the second code (that uses `runkit7_function_redefine`) is also slower than the first one, cause in my understanding maybe the second could would not need to remove the define function everytime, just change it's code, right? Because I thought the 2nd code was the way to go, but clearly the first one is the winner (at least on my Win10 machine and in my VPS running Centos).

Or am I doing something wrong?

**Comment by TysonAndre** [comment]
```
php > runkit_function_add('foo-bar', function() { echo "test\n"; });
php > 'foo-bar'();
test
```

It does a few other things, such as allowing the creation of names that otherwise wouldn't be valid identifiers (I forget if that was intentional, it's been like that for a while).
It also has the option to take closures.

But yes, in your use case eval() is faster and should be safe

**Comment by batata004** [comment]
Thank you so much, you are doing a great job!!!
