### ISSUE TITLE
runkit_function_redefine not working with internal functions

### ISSUE THREAD

**Issue by ericol** [runkit7/runkit7#28]
`runkit_function_redefine` doesn't affect internal functions.
the following code:
```
<?php
function testme() {
  echo strlen("Original Testme Implementation")."\n";
}
testme();
runkit_function_redefine('strlen','$string','return "5";');
testme();
```
Gives this result:
```
30
30
```
This is the result with `internal_override` off:
```
30
PHP Warning:  runkit_function_redefine(): strlen() is an internal function and runkit.internal_override is disabled in 2run.php on line 6
30
```
`runkit_function_redefine` doesn't work either (Except for other runkit related functions):
```
<?php
runkit_function_remove('strlen');
$var='some string to be measured';
echo "The length of '{$var}' is  ".strlen($var)."\n";
```
returns `The length of 'some string to be measured' is 26`

PHP version:
```
PHP 7.0.10-1~dotdeb+8.1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```
Regards.

**Comment by TysonAndre** [comment]
The below needs to be added to your php.ini

Also see the readme: renaming back, or replacing user functions with built in functions, will likely not work until internal overrides are finished implementing.

```
runkit.internal_override=On
```

**Comment by ericol** [comment]
@TysonAndre I have the value of `internal_override` set correctly (As a matter of fact, I tested with both settings, that's why I put 2 outputs above, one with `internal_override` set and another without: The one without is the one that gives a warning).

**Comment by TysonAndre** [comment]
I missed the first part.

It seems that php 7 does two different optimization to `strlen`. Invocations of strlen aren't using the method table(calling an internal function). They're invoking the opcode `STRLEN`

It's possible for runkit to just return false when trying to manipulate `strlen` - It would only have an effect on user code if `strlen` was used via call_user_func, etc.

Second, the php opcode compiler precalculates the value of `strlen` on constants

See https://3v4l.org/3M1jv/vld#output
```
function testme() {
  echo strlen("Original Testme Implementation")."\n";
}
```

```
Function testme:
Finding entry points
Branch analysis from position: 0
Jump found. Position 1 = -2
filename:       /in/3M1jv
function name:  testme
number of ops:  2
compiled vars:  none
line     #* E I O op                           fetch          ext  return  operands
-------------------------------------------------------------------------------------
   3     0  E >   ECHO                                                     '30%0A'
   4     1      > RETURN                                                   null
```

<hr>
And even if $x wasn't a constant, strlen is a special opcode (uses `STRLEN` opcode instead of `INIT_FCALL` opcode)

```
function testme($x) {
  echo strlen($x)."\n";
  echo json_encode($x);
}
```
```
Function testme:
Finding entry points
Branch analysis from position: 0
Jump found. Position 1 = -2
filename:       /in/XhPcP
function name:  testme
number of ops:  9
compiled vars:  !0 = $x
line     #* E I O op                           fetch          ext  return  operands
-------------------------------------------------------------------------------------
   2     0  E >   RECV                                             !0      
   3     1        STRLEN                                           ~1      !0
         2        CONCAT                                           ~2      ~1, '%0A'
         3        ECHO                                                     ~2
   4     4        INIT_FCALL                                               'json_encode'
         5        SEND_VAR                                                 !0
         6        DO_ICALL                                         $3      
         7        ECHO                                                     $3
   5     8      > RETURN                                                   null
```

**Comment by TysonAndre** [comment]
If you need to override the `strlen` opcode in particular, see https://pecl.php.net/package/uopz (http://php.net/manual/en/function.uopz-overload.php looks like it may work)

See the slides at http://www.slideshare.net/nikita_ppv/php-7-what-changed-internally-php-barcelona-2015 (page 71), this was an optimization introduced in php 7 (Strlen is used frequently, and so it was optimized to be as fast as possible).

![php-7-what-changed-internally-php-barcelona-2015-71-638](https://cloud.githubusercontent.com/assets/1904430/19745127/3b494708-9b85-11e6-920d-f6b45f7d204f.jpg)


http://image.slidesharecdn.com/php7internals-151101105627-lva1-app6891/95/php-7-what-changed-internally-php-barcelona-2015-71-638.jpg?cb=1446375542

**Comment by ericol** [comment]
@TysonAndre WOW. I mean, WOW!!!

Wasn't expecting that level of info!

In all honestly, I was testing with `strlen` because a)was a rather simple function to test b)I just copied and pasted an example I found, and used it with minor modifications.

As a matter of fact, I'm interested in replacing file access functions (e.g., `file_get_contents`), as I have a large codebase that needs to start using S3 for it's files, and I feel it would be much easier to do this than search and replace.

BTW, I also looked at uopz, and the latest (PHP7 compatible) version does not implement `uopz_overload`.

I'll check with the functions I plan on replacing and will let you know of the results.

But all in all, thank you very, very much for such a complete and complex reply.

**Comment by TysonAndre** [comment]
https://github.com/s3fs-fuse/s3fs-fuse - on Linux/Unix, FUSE may be useful (access S3 like a file system), though resource usage may be less transparent.

as mentioned in the README, there's memory leaks and issues restoring internal functions after renaming. Internal function overrides are incompletely implemented right now, and only tested with short lived CLI invocations.

**Comment by ericol** [comment]
@TysonAndre you were correct about `strlen`, I just made a test that works under PHP7:
```
$ovr=runkit_function_redefine('join', '$glue, $string', 'return my_arr_join($glue, $string);');
$arr=array('something', 'here', 'go' => array('this', 'throws', 'notice', 'without', 'runkit'), phpversion());
function my_arr_join($glue = '', $pieces) {
        foreach($pieces as $key => $val) {
                if(!is_array($val)) {
                        continue;
                }
                $pieces[$key]='('.my_arr_join($glue, $val).')';
        }
        return implode($glue, $pieces);
}
echo join(' || ', $arr)."\n";
```
Without the first line, the result is this:
```
PHP Notice:  Array to string conversion in /var/www/idibu.com/public_html/runkit.php on line 13
something || here || Array || 7.0.10-1~dotdeb+8.1
```
But when leaving that line, the results are as expected:
```
something || here || (this || throws || notice || without || runkit) || 7.0.10-1~dotdeb+8.1
```

So I'll go on my merry way now :) thank you very much for your help.
