### ISSUE TITLE
Support for 'unset(MyClass::class);' ?

### ISSUE THREAD

**Issue by IceReaper** [runkit7/runkit7#29]
We're using a plugin-architecture here for a running php websocket server. Each plugin providing a small subset of features. However the lack of unloading our plugin classes, updating them, and reloading the updated ones is resulting in the silly requirement to halt the whole application to avoid "class already exists" errors, which causes all open connections to get closed. So in theory all we need is `unset(MyClass::class);` to let the autoloader re-do its magic. As this is the only functionality we need, we could accept if all other methods are disabled due to buggy behavior.

**Comment by TysonAndre** [comment]
There's no functionality to remove classes from the class table at the moment, in this or upstream.

Hypothetically, removing a class entry would involve:

0. Loop over all classes. If at least one class is a subclass of MyClass, then give up (Remove those first)
1. Loop over all objects. If at least one object is an instance of that class or a subclass, then give up.
2. Also, if something is a ReflectionMethod, ReflectionProperty, ReflectionClass, etc., of that class or a subclass, then give up.
3. Remove the entry for `MyClass` from the class table.
4. Clear opcode caches for any oplines involving MyClass (e.g. its static methods)

Aside: `MyClass::class` is literally equivalent to `"MyClass"`. It doesn't trigger the autoloader or use the constants table.

---

Also, not sure if runkit is needed here.
Does the name of the generated class have to be MyClass? Could it instead be MyClass_01234abcd? If so, then you could probably implement `get_my_plugin('MyClass') : MyPluginInterface` doing something like the pseudocode below (missing error handling):

1. $source = file_get_contents('path/to/MyClass.php'); // or stream_get_include_path
2. $hash = md5($source);
3. $genClassName =  'MyClass_' . $hash;  // use variable $origClassName instead
4. if (class_exists($genClassName, false)) { return; }
5. $source = preg_replace('/\bMyClass\b/i', $genClassName, $source);
6. eval($source);
7. return new $genClassName(args);

**Comment by IceReaper** [comment]
The problem would occur as i need to build a custom class-loader and replace all class references by adding a versionized namespace in front of them. However this will break things as plugins may depend on other plugins, and uses its classes and interfaces for type hinting, return types etc. I need a plain functionality to remove a class from the class-map without any magic like nulling things etc.

The already constructed objects should still be there, but when creating a new instance, the class-resolver should trigger the autoloader and load the new version one. In theory a simple serialize/deserialize could be possible, but this would crash if a class is removed rather than being replaced.

I know PHP simply is not made for this, but i was hoping to find a way to get this behavior working, as this allows to swap parts of the software without realy stopping it.

Simple example: ever run a minecraft / bukkit server? You start up the server and it loads all its plugins from .jar packages. you can even unload and reload plugins, resulting in updates without kicking the players. This behavior is what we want to have in our php project. Our main socket-server with the module loader is delivered as .phar, and all the plugins are .phar files on their own, which can be loaded on runtime, but currently not unload.
