### ISSUE TITLE
Test on windows with appveyor, with --enable-zts, 7.0 and 7.1 and 7.2

### ISSUE THREAD

**Issue by TysonAndre** [runkit7/runkit7#90]
https://www.appveyor.com/docs/build-configuration/#build-matrix

**Comment by TysonAndre** [comment]
https://github.com/nikic/php-ast/blob/master/.appveyor.yml is a good reference.

**Comment by pilathraj** [comment]
I've modified the appveyor.yml, that support php7.2.
https://github.com/pilathraj/runkit7.1/blob/master/appveyor.yml 

But i am facing some syntax error in your runkit_common.c file.

**Comment by TysonAndre** [comment]
This is done via https://github.com/runkit7/runkit7/pull/134

- config.h wasn't being created for PECL builds. I don't know why (possibly something wrong with config.w32 - The way config.w32 config files are supposed to be used isn't documented clearly)
- HAVE_CONFIG_H was also false.

- I gave up and went with a workaround of setting CFLAGS_RUNKIT directly (just for windows) to enable the features. I can't think of any use cases for depending on runkit7 directly.
  (Would want to use a slightly different name to avoid macro redefinition warnings)

This uncovered a single test of `runkit_import` failing in NTS PHP builds. (https://github.com/runkit7/runkit7/issues/135)
